### ISSUE TITLE
calcium.get callback can't response to the data because callback has not the res object

### ISSUE THREAD

**Issue by Astoration** [hibiyasleep/calcium#5]
calcium.get callback can't response to the data because callback has not the res object

**Comment by hibiyasleep** [comment]
more information needed, such as, at least, arguments.

**Comment by Astoration** [comment]
``` js
router.get('/', function(req,res){
        calcium.get('B100000658', new Date().getFullYear(), new Date().getMonth()+1, function(err,doc){
                today = doc[new Date().getDate()];
                res.send(today);
        });
});
```

i used this code, but callback has not the response object

**Comment by hibiyasleep** [comment]
as referenced in #6, `calcium` does not support node v0.10, please consider upgrade your system's `node`. if you need a help to upgrade, FM me.
