### ISSUE TITLE
jsdom module can not be used

### ISSUE THREAD

**Issue by Astoration** [hibiyasleep/calcium#6]
It is necessary to change a node-jsdom module

**Comment by hibiyasleep** [comment]
Works on My Machine (aka WoMM™). What's your environment? Windows? Node/io.js < version 3?

**Comment by Astoration** [comment]
i tried to require module on Node.js(Linux/CentOS7)

**Comment by hibiyasleep** [comment]
please execute `node --version`, and copy-and-paste me

**Comment by Astoration** [comment]
`[root@koibito Server]# node --version`
`v0.10.42`

**Comment by hibiyasleep** [comment]
oh god, `calcium` only support node v4 or higher. please upgrade your node version. also, `"engines"` field of `package.json` will be added (to only work with node 4+) to next version.
